<a href="https://colab.research.google.com/github/ANGELOSD99/UTEC-Fundamentos-de-PYTHON/blob/main/ANGELO_SALES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1. Crea una lista llamada numeros_pares, que contenga los números del 1 al 100 y que contenga saltos de 2 en 2
numeros_pares=list(range(2,101,2))
print(numeros_pares)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [15]:
# 2.Agrega los números 102, 104 y 106 al final de la lista numeros_pares y luego elimina los primeros 5 números de la lista numeros_pares. Muestra la lista resultante.
# Agregar los valores 102,104 y 106 a numeros_pares
numeros_pares.extend([102,104,106])
# Eliminar los primeros 5 datos
del numeros_pares[:5]
# Resultado
print(numeros_pares)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]


In [16]:
#Crea una lista llamada resultante que contenga la raíz cuadrada de cada elemento de la lista numeros_pares usando list comprehension.
import math
#Ya se tiene la lista numeros_pares
#Crear lista resultante usando list comprhensión
resultante = [math.sqrt(num) for num in numeros_pares]
#Resultado
print(resultante)

[3.4641016151377544, 3.7416573867739413, 4.0, 4.242640687119285, 4.47213595499958, 4.69041575982343, 4.898979485566356, 5.0990195135927845, 5.291502622129181, 5.477225575051661, 5.656854249492381, 5.830951894845301, 6.0, 6.164414002968976, 6.324555320336759, 6.48074069840786, 6.6332495807108, 6.782329983125268, 6.928203230275509, 7.0710678118654755, 7.211102550927978, 7.3484692283495345, 7.483314773547883, 7.615773105863909, 7.745966692414834, 7.874007874011811, 8.0, 8.12403840463596, 8.246211251235321, 8.366600265340756, 8.48528137423857, 8.602325267042627, 8.717797887081348, 8.831760866327848, 8.94427190999916, 9.055385138137417, 9.16515138991168, 9.273618495495704, 9.38083151964686, 9.486832980505138, 9.591663046625438, 9.695359714832659, 9.797958971132712, 9.899494936611665, 10.0, 10.099504938362077, 10.198039027185569, 10.295630140987]


In [18]:
#Dada la siguiente tupla tupla_x = (“alumno”,”Pedro”,15), desempaqueta la tupla tupla_x en tres variables: x, y, z, e imprime la siguiente estructura “El alumno Pedro obtuvo la calificación de 15 usando las variables x, y, z”.
tupla_x=("alumno","pedro",15)
#Desempaquetar Tupla_x
x,y,z = tupla_x
#Resultado
print(f"El {x} {y} obtuvo la calificación de {z}")

El alumno pedro obtuvo la calificación de 15


In [19]:
#Dado el siguiente diccionario notas = {“Programacion”:15.9, “Matematica”: 15.1, “Fisica”:15.6}, escribe un bucle for que imprima cada clave y su valor en el diccionario con la siguiente estructura “Mis calificaciones en el curso de Programacion es 15.9”

notas = {"Programacion":15.9,"matematica":15.1,"Física":15.6}
#Bucle for para iterar sobre el diccionario creado
for curso, calificación in notas.items():
#Resultado
   print(f"Mis calificaciones en el curso de {curso} es {calificación}")

Mis calificaciones en el curso de Programacion es 15.9
Mis calificaciones en el curso de matematica es 15.1
Mis calificaciones en el curso de Física es 15.6


In [17]:
#Crea una matriz 1D que contenga los primeros 16 elementos de la lista numeros_pares (creada en la pregunta 1), modifique las dimensiones y convertiela en una matriz 2D con shape(4,4), calcula la suma total de los elementos de la matriz matriz 2D.
import numpy as np
#Crear la lista de los primeros 16 números pares
numeros_pares_2 = list(range(2,101,2))

primeros_16_elementos = numeros_pares_2[:16]
#Convertir lista en una matriz 2D utilizando shape (4,4)
matriz_2D = np.array(primeros_16_elementos).reshape(4,4)
#Calcular Suma total de elementos de la matriz 2D
total = np.sum(matriz_2D)

#Resultados
print("Matriz 2D:")
print(matriz_2D)
print("\nSuma total de elementos:", total)

Matriz 2D:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Suma total de elementos: 272
